# Auto-generated by dtsbox publish — do not edit
"""Standalone DTS worker for this project.

Run directly with:  python worker.py
Or via the CLI:     dtsbox worker  (recommended — handles discovery automatically)
"""
from __future__ import annotations

import asyncio
import logging
import os

from azure.identity import DefaultAzureCredential
from durabletask.azuremanaged.worker import DurableTaskSchedulerWorker

# Required — DTS scheduler runs cleanup via `dtsbox cleanup install`; worker must handle it.
from dtsbox.cron import sandbox_cleanup_orchestrator
from dtsbox.sandbox import cleanup_sandboxes

from orchestrators.batch_processor import batch_processor as _dtsbox_orchestrator_0
from orchestrators.batch_processor import square_group as _dtsbox_orchestrator_1

logging.basicConfig(level=logging.INFO)

_DTSBOX_ACTIVITIES = [
]
_DTSBOX_ORCHESTRATORS = [
    ('batch_processor', _dtsbox_orchestrator_0),
    ('square_group', _dtsbox_orchestrator_1),
]


async def main() -> None:
    endpoint = os.environ.get("ENDPOINT", "http://localhost:8080")
    taskhub = os.environ.get("TASKHUB", "default")
    credential = None if endpoint == "http://localhost:8080" else DefaultAzureCredential()
    secure = endpoint != "http://localhost:8080"

    with DurableTaskSchedulerWorker(
        host_address=endpoint,
        secure_channel=secure,
        taskhub=taskhub,
        token_credential=credential,
    ) as worker:
        for name, activity in _DTSBOX_ACTIVITIES:
            activity.__name__ = name
            worker.add_activity(activity)
        for name, orchestrator in _DTSBOX_ORCHESTRATORS:
            orchestrator.__name__ = name
            worker.add_orchestrator(orchestrator)
        # Required — DTS scheduler runs cleanup via `dtsbox cleanup install`; worker must handle it.
        worker.add_activity(cleanup_sandboxes)
        worker.add_orchestrator(sandbox_cleanup_orchestrator)
        worker.start()
        while True:
            await asyncio.sleep(1)


if __name__ == "__main__":
    asyncio.run(main())
